import Head from "next/head";
import { Inter } from "next/font/google";
import Player from "../components/player";
import Environment from "./environment";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Fantasy Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Player />
        <Environment />
      </main>
    </>
  );
}
